apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: sentinelstack
data:
  DATABASE_HOST: "postgresql-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "sentinelstack"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  LOG_LEVEL: "INFO"
